server:
  port: 9862

spring:
  application:
    name: cloud-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/githubls2002/childlike.git
          search-paths: config
          username: githubls2002
          password: github43ls
          skipSslValidation: true
      label: master
    nacos:
      discovery:
        ## 服务注册地址
        server-addr: 127.0.0.1:8848

management:
  # 端点检查（健康检查）
  endpoints:
    web:
      exposure:
        include: "*"